name: flutter_supabase_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^1.10.6
  image_picker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flex_color_scheme: ^7.1.2
  timeago: ^3.5.0

flutter:
  uses-material-design: true
